name: Publish Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'placeholder'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Build Env
        run: |
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh
          . ~/.nvm/nvm.sh
          nvm install 14.15.3
          nvm use 14.15.3

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run-script build

      - name: Copying to xircuits.io
        run: rsync -r -v build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/xircuits.io/
